name: eye_phone
description: Home security cam
publish_to: 'none'
version: 2024.02.15+5

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_webrtc: ^0.9.48+hotfix.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  shared_preferences: ^2.2.2
  permission_handler: ^11.2.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.0
  device_info_plus: ^9.1.2
  share_plus: ^7.2.2
  app_links: ^3.5.0
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  screen_brightness: ^1.0.0
  audioplayers: ^5.2.1
  in_app_purchase: ^3.1.13
  firebase_auth: ^4.17.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/launcher.png"
  image_path_ios: "assets/launcher_ios.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/siren.wav
    - assets/img/google.png